zookeeper:
  image: adronorange/zookeeper-light
  ports: 
    - "2181"
kafka:
  build: .
  ports:
    - "9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103
    KAFKA_CREATE_TOPICS: "Topic1:2:4,Topic2:1:3"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
